Add CI format, license-header, bundle-size via turbo

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -125,6 +125,81 @@ jobs:
         run: npm ci
       - name: Test typescript-compat
         run: npx turbo run test -F './packages/typescript-compat/*'
+  license-header:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+      - name: Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.tmp
+            .tmp
+          key: ${{ runner.os }}-protobuf-es-license-header-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-protobuf-es-license-header-
+      - name: NPM Install
+        run: npm ci
+      - name: Update license headers
+        run: npx turbo run license-header
+      - name: Check changed files
+        run: |
+          if [[ -n $(git status --porcelain | tee /dev/stderr) ]]; then
+            echo "::error::Formatting resulted in changed files. Please make sure this branch is up to date and run 'pnpm format'. Verify the changes are what you want and commit them."
+            git diff
+            exit 1
+          fi
+  format:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+      - name: Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.tmp
+            .tmp
+          key: ${{ runner.os }}-protobuf-es-format-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-protobuf-es-format-
+      - name: NPM Install
+        run: npm ci
+      - name: Format
+        run: npx turbo run format
+      - name: Check changed files
+        run: |
+          if [[ -n $(git status --porcelain | tee /dev/stderr) ]]; then
+            echo "::error::Formatting resulted in changed files. Please make sure this branch is up to date and run 'pnpm format'. Verify the changes are what you want and commit them."
+            git diff
+            exit 1
+          fi
+  bundle-size:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+      - name: Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.tmp
+            .tmp
+          key: ${{ runner.os }}-protobuf-es-bundle-size-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-protobuf-es-bundle-size-
+      - name: NPM Install
+        run: npm ci
+      - name: Format
+        run: npx turbo run bundle-size
+      - name: Check changed files
+        run: |
+          if [[ -n $(git status --porcelain | tee /dev/stderr) ]]; then
+            echo "::error::Formatting resulted in changed files. Please make sure this branch is up to date and run 'pnpm format'. Verify the changes are what you want and commit them."
+            git diff
+            exit 1
+          fi
   bootstrap:
     runs-on: ubuntu-20.04
     steps:
