Add CI bootstrap via turbo

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -95,7 +95,34 @@ jobs:
             ~/.tmp
             .tmp
           key: ${{ runner.os }}-protobuf-es-typescript-compat-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-protobuf-es-typescript-compat-
       - name: NPM Install
         run: npm ci
       - name: Test typescript-compat
         run: npx turbo run test -F './packages/typescript-compat/*'
+  bootstrap:
+    runs-on: ubuntu-20.04
+    steps:
+      - name: checkout
+        uses: actions/checkout@v4
+      - name: Cache
+        uses: actions/cache@v4
+        with:
+          path: |
+            ~/.tmp
+            .tmp
+          key: ${{ runner.os }}-protobuf-es-bootstrap-${{ hashFiles('package-lock.json') }}
+          restore-keys: |
+            ${{ runner.os }}-protobuf-es-bootstrap-
+      - name: NPM Install
+        run: npm ci
+      - name: Bootstrap well-known types
+        run: npx turbo run bootstrap:inject bootstrap:wkt
+      - name: Check changed files
+        run: |
+          if [[ -n $(git status --porcelain | tee /dev/stderr) ]]; then
+            echo "::error::Formatting resulted in changed files. Please make sure this branch is up to date and run 'pnpm format'. Verify the changes are what you want and commit them."
+            git diff
+            exit 1
+          fi
